DROP TABLE hospitals;

CREATE EXTERNAL TABLE hospitals
(
  provider_id string,
  hospital_name string,
  address string,
  city string,
  state string,
  zip_code string,
  county_name string,
  com_nurses_floor string,
  com_nurses_achievement string,
  com_nurses_benchmark string,
  com_nurses_baseline string,
  com_nurses_perf string,
  com_nurses_achievement_points string,
  com_nurses_improvement_points string,
  com_nurses_dimension_score string,
  com_doctors_floor string,
  com_doctors_achievement string,
  com_doctors_benchmark string,
  com_doctors_baseline string,
  com_doctors_perf string,
  com_doctors_achievement_points string,
  com_doctors_improvement_points string,
  com_doctors_dimension_score string,
  responsiveness_hospital_staff_floor string,
  responsiveness_hospital_staff_achievement string,
  responsiveness_hospital_staff_benchmark string,
  responsiveness_hospital_staff_baseline string,
  responsiveness_hospital_staff_perf string,
  responsiveness_hospital_staff_achievement_points string,
  responsiveness_hospital_staff_improvement_points string,
  responsiveness_hospital_staff_dimension_score string,
  pain_management_floor string,
  pain_management_achievement string,
  pain_management_benchmark string,
  pain_management_baseline string,
  pain_management_perf string,
  pain_management_achievement_points string,
  pain_management_improvement_points string,
  pain_management_dimension_score string,
  com_about_medicines_floor string,
  com_about_medicines_achievement string,
  com_about_medicines_benchmark string,
  com_about_medicines_baseline string,
  com_about_medicines_perf string,
  com_about_medicines_achievement_points string,
  com_about_medicines_improvement_points string,
  com_about_medicines_dimension_score string,
  cleanliness_and_quietness_hospital_environment_floor string,
  cleanliness_and_quietness_hospital_environment_achievement string,
  cleanliness_and_quietness_hospital_environment_benchmark string,
  cleanliness_and_quietness_hospital_environment_baseline string,
  cleanliness_and_quietness_hospital_environment_perf string,
  cleanliness_and_quietness_hospital_environment_achievement_points string,
  cleanliness_and_quietness_hospital_environment_improvement_points string,
  cleanliness_and_quietness_hospital_environment_dimension_score string,
  discharge_info_floor string,
  discharge_info_achievement string,
  discharge_info_benchmark string,
  discharge_info_baseline string,
  discharge_info_perf string,
  discharge_info_achievement_points string,
  discharge_info_improvement_points string,
  discharge_info_dimension_score string,
  overall_rating_of_hospital_floor string,
  overall_rating_of_hospital_achievement string,
  overall_rating_of_hospital_benchmark string,
  overall_rating_of_hospital_baseline string,
  overall_rating_of_hospital_perf string,
  overall_rating_of_hospital_achievement_points string,
  overall_rating_of_hospital_improvement_points string,
  overall_rating_of_hospital_dimension_score string,
  HCAHPS_base_score string,
  HCAHPS_consistency_score string
)

ROW FORMAT SERDE
'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES(
  "separatorChar"=",",
  "quoteChar"='"',
  "escapeChar"="\\"
)
STORED AS TEXTFILE
LOCATION "/user/w205/hospital_compare/surveys_responses"
;

